---
- hosts: "{{ target }}"
  become: yes
  gather_facts: no
  vars:
    service_main_config_file: "config/{{ survey_service }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Configuring Software repo ** {{ service_software_repo_name }} **
    yum_repository:
       name: "{{ service_software_repo_name }}" 
       enabled: yes
       gpgcheck: no
       baseurl: "{{ service_software_repo_url }}"
       description: "{{ service_software_repo_name }}"

  - name: Delete all repo data
    command: /usr/bin/yum clean all
    args:
      warn: no

  - name: Trying to get info for the repo ** {{ service_software_repo_name }} **
    command: /usr/bin/yum repolist 
    args:
      warn: no
