---
- hosts: "{{ target }}"
  become: yes
  gather_facts: no
  vars:
    service_main_config_file: "config/{{ survey_service }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: Installing software for the service ** {{ service_name }} **
    yum: name={{ item }} state=present
    with_items: "{{ service_pkgs }}"
