---
- hosts: "{{ target_http }}"
  become: yes
  gather_facts: no
  vars:
    service_main_config_file: "config/{{ survey_service_http }}_config.yml"

  vars_files:
  - "{{ service_main_config_file }}"

  tasks:
  - name: "Coping Web Content to {{ service_name }}:{{ service_config_var_document_root }}"
    copy: src=webContent/ dest="{{ service_config_var_document_root }}" backup=yes
